# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='category',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
    ]
