# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('percent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('note', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=32)),
                ('course_name', models.CharField(max_length=100)),
                ('career', models.CharField(max_length=32)),
                ('units', models.FloatField()),
                ('grading_basis', models.CharField(max_length=32)),
                ('add_consent', models.CharField(max_length=32)),
                ('drop_consent', models.CharField(max_length=32)),
                ('enroll_requirement', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=800)),
                ('learning_outcome', models.CharField(max_length=800)),
                ('course_syllabus', models.CharField(max_length=800)),
                ('feedback', models.CharField(max_length=800)),
                ('required_reading', models.CharField(max_length=800)),
                ('recommended_reading', models.CharField(max_length=800)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course'),
        ),
    ]
