# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_auto_20180104_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_consent',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='career',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_syllabus',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='drop_consent',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='enroll_requirement',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='feedback',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='grading_basis',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_outcome',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='recommended_reading',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_reading',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.FloatField(null=True),
        ),
    ]
