# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20180104_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
