# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20180104_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
